### ISSUE TITLE
On debug mode details all the folders under the excluded repos 

### ISSUE THREAD

**Issue by limor-gs** [cloudify-cosmo/repex#26]
Repex should write to output the excluded repositories on debug mode,
but actually it details all the folders under the excluded repositories. For example:
15:33:26 DEBUG - ../cloudify-build-system is excluded. Skipping...
15:33:26 DEBUG - ../cloudify-build-system/crt is excluded. Skipping...
15:33:26 DEBUG - ../cloudify-build-system/crt/tests is excluded. Skipping...
15:33:26 DEBUG - ../cloudify-build-system/crt/tests/resources is excluded. Skipping...
15:33:26 DEBUG - ../cloudify-build-system/crt/tests/resources/cloudify-test3 is excluded. Skipping...
15:33:26 DEBUG - ../cloudify-build-system/crt/tests/resources/cloudify-test3/work-copy is excluded. Skipping...
15:33:26 DEBUG - ../cloudify-build-system/crt/tests/resources/cloudify-test3/work-copy/cloudify-module is excluded. Skipping...
15:33:26 DEBUG - ../cloudify-build-system/crt/tests/resources/cloudify-test3/input is excluded. Skipping...
15:33:26 DEBUG - ../cloudify-build-system/crt/tests/resources/cloudify-test3/input/cloudify-module is excluded. Skipping...
15:33:26 DEBUG - ../cloudify-build-system/crt/tests/resources/cloudify-test3/expected-output is excluded. Skipping...
15:33:26 DEBUG - ../cloudify-build-system/crt/tests/resources/cloudify-test3/expected-output/cloudify-module is excluded. Skipping...
15:33:26 DEBUG - ../cloudify-build-system/crt/tests/resources/pypi_test is excluded. Skipping...
15:33:26 DEBUG - ../cloudify-build-system/crt/tests/resources/pypi_test/fakepackage is excluded. Skipping...
15:33:26 DEBUG - ../cloudify-build-system/crt/tests/resources/metadata is excluded. Skipping...
15:33:26 DEBUG - ../cloudify-build-system/crt/tests/resources/cloudify-test2 is excluded. Skipping...
15:33:26 DEBUG - ../cloudify-build-system/crt/tests/resources/cloudify-test2/work-copy is excluded. Skipping...
15:33:26 DEBUG - ../cloudify-build-system/crt/tests/resources/cloudify-test2/work-copy/cloudify-module is excluded. Skipping...
15:33:26 DEBUG - ../cloudify-build-system/crt/tests/resources/cloudify-test2/input is excluded. Skipping...
15:33:26 DEBUG - ../cloudify-build-system/crt/tests/resources/cloudify-test2/input/cloudify-module is excluded. Skipping...
15:33:26 DEBUG - ../cloudify-build-system/crt/tests/resources/cloudify-test2/expected-output is excluded. Skipping...
15:33:26 DEBUG - ../cloudify-build-system/crt/tests/resources/cloudify-test2/expected-output/cloudify-module is excluded. Skipping...
15:33:26 DEBUG - ../cloudify-build-system/crt/tests/resources/single-file is excluded. Skipping...
15:33:26 DEBUG - ../cloudify-build-system/crt/tests/resources/single-file/check_unchanged is excluded. Skipping...
15:33:26 DEBUG - ../cloudify-build-system/crt/tests/resources/single-file/check_changed is excluded. Skipping...
15:33:26 DEBUG - ../cloudify-build-system/crt/tests/resources/plugins-test is excluded. Skipping...
15:33:26 DEBUG - ../cloudify-build-system/crt/tests/resources/plugins-test/work-copy is excluded. Skipping...
15:33:26 DEBUG - ../cloudify-build-system/crt/tests/resources/plugins-test/input is excluded. Skipping...
15:33:26 DEBUG - ../cloudify-build-system/crt/tests/resources/plugins-test/expected-output is excluded. Skipping...
15:33:26 DEBUG - ../cloudify-build-system/config is excluded. Skipping...
15:33:26 DEBUG - ../cloudify-build-system/.git is excluded. Skipping...
15:33:26 DEBUG - ../cloudify-build-system/.git/lfs is excluded. Skipping...
15:33:26 DEBUG - ../cloudify-build-system/.git/lfs/objects is excluded. Skipping...
15:33:26 DEBUG - ../cloudify-build-system/.git/lfs/objects/50 is excluded. Skipping...
15:33:26 DEBUG - ../cloudify-build-system/.git/lfs/objects/50/f9 is excluded. Skipping...
15:33:26 DEBUG - ../cloudify-build-system/.git/lfs/objects/logs is excluded. Skipping...
15:33:26 DEBUG - ../cloudify-build-system/.git/lfs/tmp is excluded. Skipping...
15:33:26 DEBUG - ../cloudify-build-system/.git/lfs/tmp/objects is excluded. Skipping...
15:33:26 DEBUG - ../cloudify-build-system/.git/refs is excluded. Skipping...
15:33:26 DEBUG - ../cloudify-build-system/.git/refs/tags is excluded. Skipping...
15:33:26 DEBUG - ../cloudify-build-system/.git/refs/heads is excluded. Skipping...
15:33:26 DEBUG - ../cloudify-build-system/.git/refs/remotes is excluded. Skipping...
15:33:26 DEBUG - ../cloudify-build-system/.git/refs/remotes/origin is excluded. Skipping...
15:33:26 DEBUG - ../cloudify-build-system/.git/branches is excluded. Skipping...
15:33:26 DEBUG - ../cloudify-build-system/.git/objects is excluded. Skipping...
15:33:26 DEBUG - ../cloudify-build-system/.git/objects/pack is excluded. Skipping...
15:33:26 DEBUG - ../cloudify-build-system/.git/objects/info is excluded. Skipping...
15:33:26 DEBUG - ../cloudify-build-system/.git/hooks is excluded. Skipping...
15:33:26 DEBUG - ../cloudify-build-system/.git/logs is excluded. Skipping...
15:33:26 DEBUG - ../cloudify-build-system/.git/logs/refs is excluded. Skipping...
15:33:26 DEBUG - ../cloudify-build-system/.git/logs/refs/heads is excluded. Skipping...
15:33:26 DEBUG - ../cloudify-build-system/.git/logs/refs/remotes is excluded. Skipping...
15:33:26 DEBUG - ../cloudify-build-system/.git/logs/refs/remotes/origin is excluded. Skipping...
15:33:26 DEBUG - ../cloudify-build-system/.git/info is excluded. Skipping...
15:33:26 DEBUG - ../cloudify-build-system/deploy is excluded. Skipping...
15:33:26 DEBUG - ../cloudify-build-system/vagrant is excluded. Skipping...
15:33:26 DEBUG - ../cloudify-build-system/jenkins is excluded. Skipping...
15:33:26 DEBUG - ../cloudify-build-system/jenkins/backup is excluded. Skipping...
15:33:26 DEBUG - ../cloudify-diamond-snmp-extension/separate-proxy-blueprint.yaml is a match. Appending to list...
15:33:26 DEBUG - ../cloudify-diamond-snmp-extension/proxy-on-manager-blueprint.yaml is a match. Appending to list...
15:33:26 DEBUG - ../test/cloudify-build-system is excluded. Skipping...
15:33:26 DEBUG - ../test/cloudify-build-system/crt is excluded. Skipping...
15:33:26 DEBUG - ../test/cloudify-build-system/crt/tests is excluded. Skipping...
15:33:26 DEBUG - ../test/cloudify-build-system/crt/tests/resources is excluded. Skipping...
15:33:26 DEBUG - ../test/cloudify-build-system/crt/tests/resources/cloudify-test3 is excluded. Skipping...
15:33:26 DEBUG - ../test/cloudify-build-system/crt/tests/resources/cloudify-test3/work-copy is excluded. Skipping...
15:33:26 DEBUG - ../test/cloudify-build-system/crt/tests/resources/cloudify-test3/work-copy/cloudify-module is excluded. Skipping...
15:33:26 DEBUG - ../test/cloudify-build-system/crt/tests/resources/cloudify-test3/input is excluded. Skipping...
15:33:26 DEBUG - ../test/cloudify-build-system/crt/tests/resources/cloudify-test3/input/cloudify-module is excluded. Skipping...
15:33:26 DEBUG - ../test/cloudify-build-system/crt/tests/resources/cloudify-test3/expected-output is excluded. Skipping...
15:33:26 DEBUG - ../test/cloudify-build-system/crt/tests/resources/cloudify-test3/expected-output/cloudify-module is excluded. Skipping...
15:33:26 DEBUG - ../test/cloudify-build-system/crt/tests/resources/pypi_test is excluded. Skipping...
15:33:26 DEBUG - ../test/cloudify-build-system/crt/tests/resources/pypi_test/fakepackage is excluded. Skipping...
15:33:26 DEBUG - ../test/cloudify-build-system/crt/tests/resources/metadata is excluded. Skipping...
15:33:26 DEBUG - ../test/cloudify-build-system/crt/tests/resources/cloudify-test2 is excluded. Skipping...
15:33:26 DEBUG - ../test/cloudify-build-system/crt/tests/resources/cloudify-test2/work-copy is excluded. Skipping...
15:33:26 DEBUG - ../test/cloudify-build-system/crt/tests/resources/cloudify-test2/work-copy/cloudify-module is excluded. Skipping...
15:33:26 DEBUG - ../test/cloudify-build-system/crt/tests/resources/cloudify-test2/input is excluded. Skipping...
15:33:26 DEBUG - ../test/cloudify-build-system/crt/tests/resources/cloudify-test2/input/cloudify-module is excluded. Skipping...
15:33:26 DEBUG - ../test/cloudify-build-system/crt/tests/resources/cloudify-test2/expected-output is excluded. Skipping...
15:33:26 DEBUG - ../test/cloudify-build-system/crt/tests/resources/cloudify-test2/expected-output/cloudify-module is excluded. Skipping...
15:33:26 DEBUG - ../test/cloudify-build-system/crt/tests/resources/single-file is excluded. Skipping...
15:33:26 DEBUG - ../test/cloudify-build-system/crt/tests/resources/single-file/check_unchanged is excluded. Skipping...
15:33:26 DEBUG - ../test/cloudify-build-system/crt/tests/resources/single-file/check_changed is excluded. Skipping...
15:33:26 DEBUG - ../test/cloudify-build-system/crt/tests/resources/plugins-test is excluded. Skipping...
15:33:26 DEBUG - ../test/cloudify-build-system/crt/tests/resources/plugins-test/work-copy is excluded. Skipping...
15:33:26 DEBUG - ../test/cloudify-build-system/crt/tests/resources/plugins-test/input is excluded. Skipping...
15:33:26 DEBUG - ../test/cloudify-build-system/crt/tests/resources/plugins-test/expected-output is excluded. Skipping...
15:33:26 DEBUG - ../test/cloudify-build-system/config is excluded. Skipping...
15:33:26 DEBUG - ../test/cloudify-build-system/.git is excluded. Skipping...
15:33:26 DEBUG - ../test/cloudify-build-system/.git/lfs is excluded. Skipping...
15:33:26 DEBUG - ../test/cloudify-build-system/.git/lfs/objects is excluded. Skipping...
15:33:26 DEBUG - ../test/cloudify-build-system/.git/lfs/objects/50 is excluded. Skipping...
15:33:26 DEBUG - ../test/cloudify-build-system/.git/lfs/objects/50/f9 is excluded. Skipping...
15:33:26 DEBUG - ../test/cloudify-build-system/.git/lfs/objects/logs is excluded. Skipping...
15:33:26 DEBUG - ../test/cloudify-build-system/.git/lfs/tmp is excluded. Skipping...
15:33:26 DEBUG - ../test/cloudify-build-system/.git/lfs/tmp/objects is excluded. Skipping...
15:33:26 DEBUG - ../test/cloudify-build-system/.git/refs is excluded. Skipping...
15:33:26 DEBUG - ../test/cloudify-build-system/.git/refs/tags is excluded. Skipping...
15:33:26 DEBUG - ../test/cloudify-build-system/.git/refs/heads is excluded. Skipping...
15:33:26 DEBUG - ../test/cloudify-build-system/.git/refs/remotes is excluded. Skipping...
15:33:26 DEBUG - ../test/cloudify-build-system/.git/refs/remotes/origin is excluded. Skipping...
15:33:26 DEBUG - ../test/cloudify-build-system/.git/branches is excluded. Skipping...
15:33:26 DEBUG - ../test/cloudify-build-system/.git/objects is excluded. Skipping...
15:33:26 DEBUG - ../test/cloudify-build-system/.git/objects/pack is excluded. Skipping...
15:33:26 DEBUG - ../test/cloudify-build-system/.git/objects/info is excluded. Skipping...
15:33:26 DEBUG - ../test/cloudify-build-system/.git/hooks is excluded. Skipping...
15:33:26 DEBUG - ../test/cloudify-build-system/.git/logs is excluded. Skipping...
15:33:26 DEBUG - ../test/cloudify-build-system/.git/logs/refs is excluded. Skipping...
15:33:26 DEBUG - ../test/cloudify-build-system/.git/logs/refs/remotes is excluded. Skipping...
15:33:26 DEBUG - ../test/cloudify-build-system/.git/logs/refs/remotes/origin is excluded. Skipping...
15:33:26 DEBUG - ../test/cloudify-build-system/.git/info is excluded. Skipping...
15:33:26 DEBUG - ../test/cloudify-build-system/deploy is excluded. Skipping...
15:33:26 DEBUG - ../test/cloudify-build-system/vagrant is excluded. Skipping...
15:33:26 DEBUG - ../test/cloudify-build-system/jenkins is excluded. Skipping...
15:33:26 DEBUG - ../test/cloudify-build-system/jenkins/backup is excluded. Skipping...

**Comment by nir0s** [comment]
#27 solves this. it will now only print the path chosen by the user and not all skipped subdirs/files.
