### ISSUE TITLE
Versions replacement Report

### ISSUE THREAD

**Issue by limor-gs** [cloudify-cosmo/repex#34]
It is nightmare to check in a log file all the replacements strings, when the system is so complicated with a lot of versions that should be replaced.
A replacement report table can help to verify the replaced versions- 
The report table includes the below columns:
Replace (from the config file) , string before, string after, file name (full path).

**Comment by nir0s** [comment]
The current printout is much more organized, less verbose by default and provides more information. If we think in the future that we need an additional summary, let's open this up again.
