### ISSUE TITLE
Verbosity level

### ISSUE THREAD

**Issue by limor-gs** [cloudify-cosmo/repex#37]
Please add verbosity level which adds the description of each section of the config file.

**Comment by nir0s** [comment]
Please provide more info on what you'd like to see

**Comment by opencm** [comment]
For example:  in the following section please write in the beginning of the replacement -
Looking for ... for description: handles the cli dependency in setup.py

  -   description: handles the cli dependency in setup.py
        type: setup.py$
        path: "{{ .core_repos_path_regex }}"
        tags:
          - nightly
        excluded:
          - cloudify-build-system
          - test/cloudify-build-system
        base_directory: "{{ .base_dir }}"
        match: ('|")cloudify==.*('|")
        replace: "{{ .python_version_regex }}"
        with: "{{ .python_core_version }}"
